{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "@allure.feature(\"fails\")\n    def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_allure.py:12: AssertionError"}, "description": "this test fails", "start": 1700416291286, "stop": 1700416291286, "uuid": "7d6a26b9-545b-4bf7-afc1-1927cf0ef0c0", "historyId": "831c39b42e655530a19927dc1ea2cf01", "testCaseId": "831c39b42e655530a19927dc1ea2cf01", "fullName": "demo.test_allure#test_failure", "labels": [{"name": "feature", "value": "fails"}, {"name": "parentSuite", "value": "demo"}, {"name": "suite", "value": "test_allure"}, {"name": "host", "value": "LAPTOP-J67UEDPK"}, {"name": "thread", "value": "57656-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "demo.test_allure"}]}